from .file import *
from .process import *
from .echarts import *
from .setTask import *
from .webssh import *
from .login import *
#from .plugins import *
from .controlPanel import *
from .linkButton import *